name: Build PS4 Stage2 12.50

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc-multilib g++-multilib clang

    - name: Compile Stage2 for 12.50
      run: |
        make clean
        make FIRMWARE=1250

    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: stage2-1250-binary
        path: stage2.bin
